# Generated by Django 2.2.5 on 2020-12-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='cookies',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
